import type { ComponentType, SVGProps } from "react"
import {
  Afghanistan,
  AlandIslands,
  Albania,
  Algeria,
  AmericanSamoa,
  Andorra,
  Angola,
  Anguilla,
  AntiguaAndBarbuda,
  Argentina,
  Armenia,
  Aruba,
  Australia,
  Austria,
  Azerbaijan,
  Bahamas,
  Bahrain,
  Bangladesh,
  Barbados,
  Belarus,
  Belgium,
  Belize,
  Benin,
  Bermuda,
  Bhutan,
  Bolivia,
  Bonaire,
  BosniaAndHerzegovina,
  Botswana,
  Brazil,
  BritishIndianOceanTerritory,
  BritishVirginIslands,
  Brunei,
  Bulgaria,
  BurkinaFaso,
  Burundi,
  Cambodia,
  Cameroon,
  Canada,
  CapeVerde,
  CaymanIslands,
  CentralAfricanRepublic,
  Chad,
  Chile,
  China,
  ChristmasIsland,
  CocosIsland,
  Colombia,
  Comoros,
  CookIslands,
  CostaRica,
  Croatia,
  Cuba,
  Curacao,
  Cyprus,
  CzechRepublic,
  DemocraticRepublicOfCongo,
  Denmark,
  Djibouti,
  Dominica,
  DominicanRepublic,
  EastTimor,
  Ecuador,
  Egypt,
  ElSalvador,
  EquatorialGuinea,
  Eritrea,
  Estonia,
  Ethiopia,
  EuropeanUnion,
  FalklandIslands,
  FaroeIslands,
  Fiji,
  Finland,
  France,
  FrenchPolynesia,
  Gabon,
  Gambia,
  Georgia,
  Germany,
  Ghana,
  Gibraltar,
  Greece,
  Greenland,
  Grenada,
  Guam,
  Guatemala,
  Guernsey,
  Guinea,
  GuineaBissau,
  Guyana,
  Haiti,
  Honduras,
  HongKong,
  Hungary,
  Iceland,
  India,
  Indonesia,
  Iran,
  Iraq,
  Ireland,
  IsleOfMan,
  Israel,
  Italy,
  IvoryCoast,
  Jamaica,
  Japan,
  Jersey,
  Jordan,
  Kazakhstan,
  Kenya,
  Kiribati,
  Kosovo,
  Kuwait,
  Kyrgyzstan,
  Laos,
  Latvia,
  Lebanon,
  Lesotho,
  Liberia,
  Libya,
  Liechtenstein,
  Lithuania,
  Luxembourg,
  Macao,
  Madagascar,
  Malawi,
  Malaysia,
  Maldives,
  Mali,
  Malta,
  MarshallIsland,
  Martinique,
  Mauritania,
  Mauritus,
  Mexico,
  Micronesia,
  Moldova,
  Monaco,
  Mongolia,
  Montenegro,
  Montserrat,
  Morocco,
  Mozambique,
  Myanmar,
  Namibia,
  Nauru,
  Nepal,
  Netherlands,
  NewZealand,
  Nicaragua,
  Niger,
  Nigeria,
  Niue,
  NorfolkIsland,
  NorthernMarianasIslands,
  NorthKorea,
  Norway,
  Oman,
  Pakistan,
  Palau,
  Palestine,
  Panama,
  PapuaNewGuinea,
  Paraguay,
  Peru,
  Philippines,
  PitcairnIslands,
  Poland,
  Portugal,
  PuertoRico,
  Qatar,
  RepublicOfMacedonia,
  RepublicOfTheCongo,
  Romania,
  Russia,
  Rwanda,
  SahrawiArabDemocraticRepublic,
  SaintKittsAndNevis,
  Samoa,
  SanMarino,
  SaoTomeAndPrince,
  SaudiArabia,
  Senegal,
  Serbia,
  Seychelles,
  SierraLeone,
  Singapore,
  SintMaarten,
  Slovakia,
  Slovania,
  SolomonIslands,
  Somalia,
  SouthAfrica,
  SouthKorea,
  SouthSudan,
  Spain,
  SriLanka,
  StBarts,
  StLucia,
  StVincentAndTheGrenadines,
  Sudan,
  Suriname,
  Swaziland,
  Sweden,
  Switzerland,
  Syria,
  Taijikistan,
  Taiwan,
  Tanzania,
  Thailand,
  Togo,
  Tokelau,
  Tonga,
  TrinidadAndTobago,
  Tunisia,
  Turkey,
  Turkmenistan,
  TurksAndCaicos,
  Tuvalu,
  Uganda,
  Ukraine,
  UnitedArabEmirates,
  UnitedKingdom,
  UnitedStates,
  Uruguay,
  Uzbekistn,
  Vanuatu,
  VaticanCity,
  Venezuela,
  Vietnam,
  VirginIslands,
  Yemen,
  Zambia,
  Zimbabwe,
} from "@create-ui/assets/flags"

export type FlagComponent = ComponentType<SVGProps<SVGSVGElement>>

/**
 * ISO 3166-1 alpha-2 country code → SVG flag component, plus the supranational
 * `EU` (European Union) code which is not part of ISO 3166-1 but is needed for
 * the EUR currency. Codes are uppercase; lookups via {@link getCountryFlag}
 * normalize input case.
 */
export const COUNTRY_FLAGS: Record<string, FlagComponent> = {
  AD: Andorra,
  AE: UnitedArabEmirates,
  AF: Afghanistan,
  AG: AntiguaAndBarbuda,
  AI: Anguilla,
  AL: Albania,
  AM: Armenia,
  AO: Angola,
  AR: Argentina,
  AS: AmericanSamoa,
  AT: Austria,
  AU: Australia,
  AW: Aruba,
  AX: AlandIslands,
  AZ: Azerbaijan,
  BA: BosniaAndHerzegovina,
  BB: Barbados,
  BD: Bangladesh,
  BE: Belgium,
  BF: BurkinaFaso,
  BG: Bulgaria,
  BH: Bahrain,
  BI: Burundi,
  BJ: Benin,
  BL: StBarts,
  BM: Bermuda,
  BN: Brunei,
  BO: Bolivia,
  BQ: Bonaire,
  BR: Brazil,
  BS: Bahamas,
  BT: Bhutan,
  BW: Botswana,
  BY: Belarus,
  BZ: Belize,
  CA: Canada,
  CC: CocosIsland,
  CD: DemocraticRepublicOfCongo,
  CF: CentralAfricanRepublic,
  CG: RepublicOfTheCongo,
  CH: Switzerland,
  CI: IvoryCoast,
  CK: CookIslands,
  CL: Chile,
  CM: Cameroon,
  CN: China,
  CO: Colombia,
  CR: CostaRica,
  CU: Cuba,
  CV: CapeVerde,
  CW: Curacao,
  CX: ChristmasIsland,
  CY: Cyprus,
  CZ: CzechRepublic,
  DE: Germany,
  DJ: Djibouti,
  DK: Denmark,
  DM: Dominica,
  DO: DominicanRepublic,
  DZ: Algeria,
  EC: Ecuador,
  EE: Estonia,
  EG: Egypt,
  EH: SahrawiArabDemocraticRepublic,
  ER: Eritrea,
  ES: Spain,
  ET: Ethiopia,
  EU: EuropeanUnion,
  FI: Finland,
  FJ: Fiji,
  FK: FalklandIslands,
  FM: Micronesia,
  FO: FaroeIslands,
  FR: France,
  GA: Gabon,
  GB: UnitedKingdom,
  GD: Grenada,
  GE: Georgia,
  GG: Guernsey,
  GH: Ghana,
  GI: Gibraltar,
  GL: Greenland,
  GM: Gambia,
  GN: Guinea,
  GQ: EquatorialGuinea,
  GR: Greece,
  GT: Guatemala,
  GU: Guam,
  GW: GuineaBissau,
  GY: Guyana,
  HK: HongKong,
  HN: Honduras,
  HR: Croatia,
  HT: Haiti,
  HU: Hungary,
  ID: Indonesia,
  IE: Ireland,
  IL: Israel,
  IM: IsleOfMan,
  IN: India,
  IO: BritishIndianOceanTerritory,
  IQ: Iraq,
  IR: Iran,
  IS: Iceland,
  IT: Italy,
  JE: Jersey,
  JM: Jamaica,
  JO: Jordan,
  JP: Japan,
  KE: Kenya,
  KG: Kyrgyzstan,
  KH: Cambodia,
  KI: Kiribati,
  KM: Comoros,
  KN: SaintKittsAndNevis,
  KP: NorthKorea,
  KR: SouthKorea,
  KW: Kuwait,
  KY: CaymanIslands,
  KZ: Kazakhstan,
  LA: Laos,
  LB: Lebanon,
  LC: StLucia,
  LI: Liechtenstein,
  LK: SriLanka,
  LR: Liberia,
  LS: Lesotho,
  LT: Lithuania,
  LU: Luxembourg,
  LV: Latvia,
  LY: Libya,
  MA: Morocco,
  MC: Monaco,
  MD: Moldova,
  ME: Montenegro,
  MG: Madagascar,
  MH: MarshallIsland,
  MK: RepublicOfMacedonia,
  ML: Mali,
  MM: Myanmar,
  MN: Mongolia,
  MO: Macao,
  MP: NorthernMarianasIslands,
  MQ: Martinique,
  MR: Mauritania,
  MS: Montserrat,
  MT: Malta,
  MU: Mauritus,
  MV: Maldives,
  MW: Malawi,
  MX: Mexico,
  MY: Malaysia,
  MZ: Mozambique,
  NA: Namibia,
  NE: Niger,
  NF: NorfolkIsland,
  NG: Nigeria,
  NI: Nicaragua,
  NL: Netherlands,
  NO: Norway,
  NP: Nepal,
  NR: Nauru,
  NU: Niue,
  NZ: NewZealand,
  OM: Oman,
  PA: Panama,
  PE: Peru,
  PF: FrenchPolynesia,
  PG: PapuaNewGuinea,
  PH: Philippines,
  PK: Pakistan,
  PL: Poland,
  PN: PitcairnIslands,
  PR: PuertoRico,
  PS: Palestine,
  PT: Portugal,
  PW: Palau,
  PY: Paraguay,
  QA: Qatar,
  RO: Romania,
  RS: Serbia,
  RU: Russia,
  RW: Rwanda,
  SA: SaudiArabia,
  SB: SolomonIslands,
  SC: Seychelles,
  SD: Sudan,
  SE: Sweden,
  SG: Singapore,
  SI: Slovania,
  SK: Slovakia,
  SL: SierraLeone,
  SM: SanMarino,
  SN: Senegal,
  SO: Somalia,
  SR: Suriname,
  SS: SouthSudan,
  ST: SaoTomeAndPrince,
  SV: ElSalvador,
  SX: SintMaarten,
  SY: Syria,
  SZ: Swaziland,
  TC: TurksAndCaicos,
  TD: Chad,
  TG: Togo,
  TH: Thailand,
  TJ: Taijikistan,
  TK: Tokelau,
  TL: EastTimor,
  TM: Turkmenistan,
  TN: Tunisia,
  TO: Tonga,
  TR: Turkey,
  TT: TrinidadAndTobago,
  TV: Tuvalu,
  TW: Taiwan,
  TZ: Tanzania,
  UA: Ukraine,
  UG: Uganda,
  US: UnitedStates,
  UY: Uruguay,
  UZ: Uzbekistn,
  VA: VaticanCity,
  VC: StVincentAndTheGrenadines,
  VE: Venezuela,
  VG: BritishVirginIslands,
  VI: VirginIslands,
  VN: Vietnam,
  VU: Vanuatu,
  WS: Samoa,
  XK: Kosovo,
  YE: Yemen,
  ZA: SouthAfrica,
  ZM: Zambia,
  ZW: Zimbabwe,
}

export function getCountryFlag(code: string): FlagComponent | undefined {
  return COUNTRY_FLAGS[code.toUpperCase()]
}
